[package]
name = "boppo_wasm"
version = "0.1.1"
edition = "2024"
description = "Activity API for the Boppo Tablet, controlling the lights, buttons, and audio via a WASM module."
homepage = "https://developer.boppo.com"
keywords = ["boppo", "wasm", "audio", "embedded", "led"]
categories = ["api-bindings", "wasm"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/boppofun/rust_boppo_wasm"

[dependencies]
boppo_core = { version = "0.2.0", features = ["wasm"] }
# boppo_core = { git = "https://github.com/boppofun/rust_boppo_core", rev = "15561980", features = ["wasm"] }
edge-executor = "0.4.1"
embassy-time-driver = "0.2.2"
serde_json = "1.0.128"
tokio = { version = "1.21", features = ["sync"] }

# [patch."https://github.com/boppofun/rust_boppo_core"]
# boppo_core = { path = "../rust_boppo_core" }
